### ISSUE TITLE
Ancient version of rayon

### ISSUE THREAD

**Issue by RalfJung** [AndrewRadev/id3-image#1]
This crate came up during testing for https://github.com/rust-lang/rust/pull/71274 as being affected by better detection of misuse of uninitialized memory. I think the reason is that the lockfile pins the dependency of rayon to the ancient version 1.0, which in turn depends on crossbeam-epoch 0.3, which contains many issues that have been fixed over the last 2 years.

Would be great if you could update your lockfile to make sure you get all those fixes. :) `cargo update` is all it should take.

**Comment by AndrewRadev** [comment]
Thank you for reaching out with an explanation of the problem. The project uses a very small subset of its dependencies, so thankfully, it was quite easy to even bump the versions in the `Cargo.toml` with only one code fix: https://github.com/AndrewRadev/id3-image/commit/b818a59424de9cb8a57a8a7b600966ed4ad22df9

With this, the version of rayon is 1.4.0, and crossbeam-epoch is at 0.8.2, both of which seem to be their latest, so I'll consider the issue resolved for now. I've pushed a new version to crates.io as well.
